# Site settings
title: YORE
author:
  name: Maryam Kargaran
  email: blogforyore@gmail.com
description: "Solution Design in Medical Engineering Summer 2022"

# Build settings
remote_theme: jekyll/minima
